config/routes.rb
Rails.application.routes.draw do
  root to: "words#index"
  resources :words
  get 'test', to: "test#run"
end

app/models/language.rb
# == Schema Information
#
# Table name: languages
#
#  id         :integer          not null, primary key
#  name       :string
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class Language < ActiveRecord::Base
  validates :name, presence: true, uniqueness: true
  has_many :words

  def to_s
    name
  end

  def self.options
    all.map {|x| [x.name, x.id]}
  end
end

app/models/word.rb
# == Schema Information
#
# Table name: words
#
#  id             :integer          not null, primary key
#  name           :string
#  part_of_speech :string
#  translation    :string
#  language_id    :integer
#  created_at     :datetime         not null
#  updated_at     :datetime         not null
#

class Word < ActiveRecord::Base
  PARTS_OF_SPEECH = %w(Noun Verb Adjective Adverb).freeze
  validates :name, presence: true, uniqueness: true
  validates :part_of_speech, presence: true, inclusion: {in: PARTS_OF_SPEECH}
  validates :translation, presence: true
  belongs_to :language

  def to_s
    name
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/test_controller.rb
class TestController < ApplicationController
  def run
  end
end

app/controllers/words_controller.rb
class WordsController < ApplicationController
  def index
    @word = Word.new
    @words = Word.all
    @languages = Language.options
  end

  def create
    word = Word.new(word_params)
    unless word.save
      flash[:alert] = word.errors.full_messages
    end
    redirect_to words_path
  end

  def word_params
    params.require(:word).permit(:name, :part_of_speech, :translation, :language_id)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/test_helper.rb
module TestHelper
end

app/helpers/webpack_helper.rb
module WebpackHelper
  def webpack_include_tag(asset, options = {})
    options = options.reverse_merge(
      src: webpack_asset_path(asset, 'js'),
      type: 'text/javascript'
    )
    content_tag(:script, nil, options) if options[:src]
  end

  def webpack_asset_path(path, ext)
    path = Regexp.escape(path)
    ext = Regexp.escape(ext)
    hashed_asset = webpack_asset(/\A#{path}-\w+\.#{ext}\z/)
    unhashed_asset = webpack_asset(/\A#{path}\.#{ext}\z/)
    asset = hashed_asset || unhashed_asset
    p asset
    p File.join('/', webpack_path, asset).to_s
    File.join('/', webpack_path, asset).to_s if asset
  end

  def webpack_asset(pattern)
    webpack_assets.find { |f| f.to_path =~ pattern }
  end

  def webpack_assets
    Dir[File.join(webpack_directory, '**/*')]
      .sort_by { |f| File.mtime(f) }.reverse
      .map { |f| Pathname.new(f).relative_path_from(webpack_directory) }
  end

  def webpack_path
    webpack_directory.relative_path_from(Rails.root.join('public'))
  end

  def webpack_directory
    Pathname.new Rails.application.config.x.webpack.path
  end
end

app/helpers/words_helper.rb
module WordsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>FlashCards</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= webpack_include_tag 'testApp.bundle' %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/words/index.html.erb
<%= flash.alert %>
<div class="word-form">
  <%= form_for @word, url: { action: "create" } do |f| %>
    <div>
      <%= f.label :word %>
      <%= f.text_field :name %>
    </div>
    <div>
      <%= f.label :part_of_speech %>
      <%= f.select :part_of_speech, Word::PARTS_OF_SPEECH %>
    </div>
    <div>
      <%= f.label :translation %>
      <%= f.text_field :translation %>
    </div>
    <div>
      <%= f.label :language %>
      <%= f.select :language_id, @languages %>
    </div>
    <%= f.submit :save %>
  <% end %>
</div>

<div class="word-container">
  <% @words.each do |word| %>
    <div class="card">
      <div class="word">
        <%= word %>
      </div>
      <div class="part-of-speech">
        <%= word.part_of_speech %>
      </div>
      <div class="meaning">
        <%= word.translation %>
      </div>
      <div class="language">
        <%= word.language %>
      </div>
      
    </div>
  <% end %>
</div>

<button class="start-test">
  <%= link_to "Run a test", test_path %>
</button>